

import dbcontext.DatabaseHelper;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;

public class DatabaseHelperTest {

    private static Connection connection;
    private static DatabaseHelper dbHelper;

    @BeforeAll
    public static void setup() throws SQLException {
        // Use H2 in‑memory database
        String url = "jdbc:h2:mem:test;DB_CLOSE_DELAY=-1";
        connection = DriverManager.getConnection(url, "sa", "");
        Statement stmt = connection.createStatement();
        // Create a test table
        stmt.execute("CREATE TABLE test_table (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255))");
        stmt.execute("INSERT INTO test_table (name) VALUES ('Alice'), ('Bob')");
        stmt.close();

        dbHelper = new DatabaseHelper(url, "sa", "");
    }

    @AfterAll
    public static void teardown() throws SQLException {
        Statement stmt = connection.createStatement();
        stmt.execute("DROP TABLE test_table");
        stmt.close();
        connection.close();
    }

    @Test
    public void testExecuteSelectSimpleType() throws SQLException {
        List<String> names = dbHelper.executeSelect("SELECT name FROM test_table", String.class);
        assertNotNull(names);
        assertEquals(3, names.size());
        assertTrue(names.contains("Charlie"));
        assertTrue(names.contains("Bob"));
        assertTrue(names.contains("David"));
    }

    @Test
    public void testExecuteSelectMappingToDTO() throws SQLException {
        List<TestDTO> dtos = dbHelper.executeSelect("SELECT id, name FROM test_table", TestDTO.class);
        assertNotNull(dtos);
        assertEquals(3, dtos.size());
        for (TestDTO dto : dtos) {
            assertNotEquals(0, dto.id);
            assertNotNull(dto.name);
        }
    }

    @Test
    public void testExecuteUpdate() throws SQLException {
        int rowsAffected = dbHelper.executeUpdate("UPDATE test_table SET name = ? WHERE name = ?", "Charlie", "Alice");
        assertEquals(1, rowsAffected);
        List<String> names = dbHelper.executeSelect("SELECT name FROM test_table WHERE name = 'Charlie'", String.class);
        assertEquals(1, names.size());
        assertEquals("Charlie", names.get(0));
    }

//    @Test
//    public void testExecuteUpdateGeneratedKeys() throws SQLException {
//        DatabaseHelper.IntSet result = dbHelper.executeUpdateGeneratedKeys("INSERT INTO test_table (name) VALUES (?)", "David");
//        assertEquals(1, result.rowsAffected());
//        assertTrue(result.autoGeneratedId() > 0);
//        List<String> names = dbHelper.executeSelect("SELECT name FROM test_table WHERE id = ?", String.class, result.autoGeneratedId());
//        assertEquals(1, names.size());
//        assertEquals("David", names.get(0));
//    }

    // Dummy DTO for testing mapping
    public static class TestDTO {
        public int id;
        public String name;
        public TestDTO() {}
    }
}